
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtris-deployment
  labels:
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
        app: techtris
    spec:
      spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - techtris
              topologyKey: kubernetes.io/hostname
      containers:
      - name: app
        image: "{{ image_id }}"
        resources:
          requests:
            cpu: 10m